AWSTemplateFormatVersion: '2010-09-09'
Description: Configuration for Streamlit production environment with DynamoDB

Parameters:
  KeyName:
    Type: String
    Description: Name of the SSH key pair for EC2 access
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
  OpenAIAPIKey:
    Type: String
    Description: OpenAI API Key for the application
    NoEcho: true  # Hides the value from being displayed in plain text
  PineconeAPIKey:
    Type: String
    Description: Pinecone API Key for the application
    NoEcho: true  # Hides the value from being displayed in plain text
    
Resources:
  # VPC
  ProdVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: prod-vpc

  # Subnets
  ProdPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdVPC
      CidrBlock: 10.1.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: prod-public-subnet

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ProdVPC
      InternetGatewayId: !Ref InternetGateway

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProdVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref ProdPublicSubnet

  # Security Group for EC2
  ProdSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance
      VpcId: !Ref ProdVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  ProdInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref ProdSecurityGroup
      SubnetId: !Ref ProdPublicSubnet
      ImageId: ami-0c80e2b6ccb9ad6d1  # Amazon Linux 2023 AMI
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            sudo yum update -y
            # Install Git
            sudo yum install -y git
            # Ensure pip is installed and upgrade it
            sudo python3 -m ensurepip --upgrade
            sudo python3 -m pip install --upgrade pip
            # Clone and set up the application
            cd /home/ec2-user
            git clone https://github.com/talesitf/cautious-enigma.git streamlit_app
            cd streamlit_app
            git checkout test
            sudo git config --global --add safe.directory /home/ec2-user/streamlit_app
            # Install dependencies from requirements.txt
            pip3 install -r requirements.txt
            # Set environment variables
            sudo sh -c "echo 'DYNAMODB_TABLE=test_streamlit_table' >> /etc/environment"
            sudo sh -c "echo 'APP_ENV=test' >> /etc/environment"
            sudo sh -c "echo 'OPENAI_API_KEY=${OpenAIAPIKey}' >> /etc/environment"
            sudo sh -c "echo 'PINECONE_API_KEY=${PineconeAPIKey}' >> /etc/environment"
            # Start the Streamlit application
            nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 > streamlit.log 2>&1 &

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prod_streamlit_table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: Prod

Outputs:
  InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt ProdInstance.PublicIp

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTable
